### ISSUE TITLE
invalid double, Range out of index , Bad State error occurs with this plugin.

### ISSUE THREAD

**Issue by devopsflutter** [sergiotucano/digital_scale#1]
invalid double, Range out of index , Bad State error occurs with this plugin.

**Comment by Birjesh1998** [comment]
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
E/flutter (16226): 0.125
E/flutter (16226): 00.125
E/flutter (16226): 00.125
E/flutter (16226): 00.125
E/flutter (16226): 00.125
E/flutter (16226): 00.125
E/flutter (16226): 00.125
E/flutter (16226): #0      double.parse (dart:core-patch/double_patch.dart:112:28)
E/flutter (16226): #1      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:146:27)
E/flutter (16226): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/flutter (16226): Message null
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/chatty  (16226): uid=10141(com.soulbook.metapos) 1.ui identical 117 lines
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/DartWorker(16226): type=1400 audit(0.0:3841): avc: denied { getattr } for path="/dev/ttyUSB0" dev="tmpfs" ino=1464 scontext=u:r:untrusted_app:s0:c141,c256,c512,c768 tcontext=u:object_r:usb_serial_device:s0 tclass=chr_file permissive=1 app=com.soulbook.metapos
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/chatty  (16226): uid=10141(com.soulbook.metapos) 1.ui identical 8 lines
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
E/flutter (16226): 
E/flutter (16226): #0      double.parse (dart:core-patch/double_patch.dart:112:28)
E/flutter (16226): #1      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:146:27)
E/flutter (16226): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/chatty  (16226): uid=10141(com.soulbook.metapos) 1.ui identical 30 lines
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Future already completed
E/flutter (16226): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
E/flutter (16226): #1      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:151:19)
E/flutter (16226): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/chatty  (16226): uid=10141(com.soulbook.metapos) 1.ui identical 14 lines
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
E/flutter (16226): 
E/flutter (16226): #0      double.parse (dart:core-patch/double_patch.dart:112:28)
E/flutter (16226): #1      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:146:27)
E/flutter (16226): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/chatty  (16226): uid=10141(com.soulbook.metapos) 1.ui identical 6 lines
E/flutter (16226): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Only valid value is 1: 0
E/flutter (16226): #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
E/flutter (16226): #1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
E/flutter (16226): #2      DigitalScale.getWeight.<anonymous closure> (package:digital_scale/src/digital_scale.dart:141:16)
E/flutter (16226): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (16226): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16226): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (16226): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (16226): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (16226): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16226): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16226): 
I/flutter (16226): Get weight and weight 0.0

**Comment by Birjesh1998** [comment]
I am using CAS PR-U Weighing Scale

**Comment by sergiotucano** [comment]
invalid double was corrected in https://github.com/sergiotucano/digital_scale/commit/9684891d47bc5ff4463ce9a76f95e036ec602983
